### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/toolchain-builder#12]
We need to update the [banner]( https://github.com/wpilibsuite/toolchain-builder/blob/2018/windows/makes/msi-files/banner.bmp) so it has the new FRC logo.  We might also consider putting our logo on there too.

**Comment by ThadHouse** [comment]
The windows banner is gone, so this only needs to be added to the mac installer. Which will depend on #21

**Comment by ThadHouse** [comment]
The mac installer was removed, so this can be closed.
