### ISSUE TITLE
Update pkg with current year and info

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/toolchain-builder#13]
For Mac

**Comment by ThadHouse** [comment]
#21 Updates the current year, but there is probably more you'll want to do.

**Comment by PeterJohnson** [comment]
Closed by #26 I think.

**Comment by AustinShalit** [comment]
Not quite... we need to update this file too: https://github.com/wpilibsuite/toolchain-builder/blob/2019/mac/makes/pkg/FRC%20ARM%20Toolchain.packproj

**Comment by ThadHouse** [comment]
The contents of that file were updated just the name of it wasn't.

Also, depending on how the archive goes we might get rid of the installer for Mac as well. It's not as needed with gradlerio. And breaks occasiaonally

**Comment by ThadHouse** [comment]
Since the mac package is completely gone this can be closed.
