### ISSUE TITLE
toolchain install problem ubuntu 18.04

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/toolchain-builder#19]
_From @jath03 on September 1, 2018 17:49_

The `wpilib/toolchain` ppa has packages for ubuntu 18.04 bionic beaver, but when I try to install `frc-toolchain` it gives a dependency error.  After some googling, it looks like a similar problem to [this one](https://www.chiefdelphi.com/forums/showthread.php?t=161025). I tested it on ubuntu 16.04 and it installs fine, but on 18.04 it doesn't install.

_Copied from original issue: wpilibsuite/allwpilib#1297_

**Comment by jath03** [comment]
Could I get an update on this?  "Working on it, should be fixed in a few days" or "Busy right now, will work on it when I can" or "Just saw this" or "Should be fixed now"  ????

**Comment by byteit101** [comment]
Hmm, I though this worked. I remember testing it. Will look into this...

**Comment by jath03** [comment]
???

**Comment by byteit101** [comment]
Ah! The new versions aren't Debian versions! Not sure how I managed to miss that... Busy tomorrow. Will fix probably friday after work.

**Comment by jath03** [comment]
Anything?

**Comment by jath03** [comment]
^

**Comment by byteit101** [comment]
Updated packages have synced. Should work now. Close if it works for you

**Comment by jath03** [comment]
It works!  Thanks

**Comment by ThadHouse** [comment]
Based on the above comment I'm going to close this.
